//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store.Win.Tests.Resources {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Icons48 {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Icons48() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Store.Win.Tests.Resources.Icons48", typeof(Icons48).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		internal static System.Drawing.Bitmap _lock {
			get {
				object obj = ResourceManager.GetObject("lock", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap accept {
			get {
				object obj = ResourceManager.GetObject("accept", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap add {
			get {
				object obj = ResourceManager.GetObject("add", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap addfile {
			get {
				object obj = ResourceManager.GetObject("addfile", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap adduser {
			get {
				object obj = ResourceManager.GetObject("adduser", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap app {
			get {
				object obj = ResourceManager.GetObject("app", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap back {
			get {
				object obj = ResourceManager.GetObject("back", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap backward {
			get {
				object obj = ResourceManager.GetObject("backward", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap bug {
			get {
				object obj = ResourceManager.GetObject("bug", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap burn {
			get {
				object obj = ResourceManager.GetObject("burn", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap cd {
			get {
				object obj = ResourceManager.GetObject("cd", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap chat {
			get {
				object obj = ResourceManager.GetObject("chat", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap clock {
			get {
				object obj = ResourceManager.GetObject("clock", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap close {
			get {
				object obj = ResourceManager.GetObject("close", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap configure {
			get {
				object obj = ResourceManager.GetObject("configure", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap console {
			get {
				object obj = ResourceManager.GetObject("console", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap cut {
			get {
				object obj = ResourceManager.GetObject("cut", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap cutb {
			get {
				object obj = ResourceManager.GetObject("cutb", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap database {
			get {
				object obj = ResourceManager.GetObject("database", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap delete {
			get {
				object obj = ResourceManager.GetObject("delete", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap deletefile {
			get {
				object obj = ResourceManager.GetObject("deletefile", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap deleteuser {
			get {
				object obj = ResourceManager.GetObject("deleteuser", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap documentsorcopy {
			get {
				object obj = ResourceManager.GetObject("documentsorcopy", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap down {
			get {
				object obj = ResourceManager.GetObject("down", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap edit {
			get {
				object obj = ResourceManager.GetObject("edit", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap fav {
			get {
				object obj = ResourceManager.GetObject("fav", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap favadd {
			get {
				object obj = ResourceManager.GetObject("favadd", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap favb {
			get {
				object obj = ResourceManager.GetObject("favb", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap favbadd {
			get {
				object obj = ResourceManager.GetObject("favbadd", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap file {
			get {
				object obj = ResourceManager.GetObject("file", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap filelocked {
			get {
				object obj = ResourceManager.GetObject("filelocked", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap filesearch {
			get {
				object obj = ResourceManager.GetObject("filesearch", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap find {
			get {
				object obj = ResourceManager.GetObject("find", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap floppy {
			get {
				object obj = ResourceManager.GetObject("floppy", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap folder {
			get {
				object obj = ResourceManager.GetObject("folder", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap folderlocked {
			get {
				object obj = ResourceManager.GetObject("folderlocked", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap foldermove {
			get {
				object obj = ResourceManager.GetObject("foldermove", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap folderopenb {
			get {
				object obj = ResourceManager.GetObject("folderopenb", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap foldersearch {
			get {
				object obj = ResourceManager.GetObject("foldersearch", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap forward {
			get {
				object obj = ResourceManager.GetObject("forward", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap gotoapp {
			get {
				object obj = ResourceManager.GetObject("gotoapp", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap gowebsite {
			get {
				object obj = ResourceManager.GetObject("gowebsite", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap groupofusers {
			get {
				object obj = ResourceManager.GetObject("groupofusers", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hd {
			get {
				object obj = ResourceManager.GetObject("hd", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hdlocked {
			get {
				object obj = ResourceManager.GetObject("hdlocked", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hdsearch {
			get {
				object obj = ResourceManager.GetObject("hdsearch", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap help {
			get {
				object obj = ResourceManager.GetObject("help", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap home {
			get {
				object obj = ResourceManager.GetObject("home", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap infoabout {
			get {
				object obj = ResourceManager.GetObject("infoabout", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap key {
			get {
				object obj = ResourceManager.GetObject("key", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap mail {
			get {
				object obj = ResourceManager.GetObject("mail", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap mailpgp {
			get {
				object obj = ResourceManager.GetObject("mailpgp", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap mailsend {
			get {
				object obj = ResourceManager.GetObject("mailsend", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap money {
			get {
				object obj = ResourceManager.GetObject("money", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap moneyb {
			get {
				object obj = ResourceManager.GetObject("moneyb", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap moneyc {
			get {
				object obj = ResourceManager.GetObject("moneyc", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap movefile {
			get {
				object obj = ResourceManager.GetObject("movefile", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap music {
			get {
				object obj = ResourceManager.GetObject("music", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap network {
			get {
				object obj = ResourceManager.GetObject("network", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap networkoptions {
			get {
				object obj = ResourceManager.GetObject("networkoptions", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap networksearch {
			get {
				object obj = ResourceManager.GetObject("networksearch", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap next {
			get {
				object obj = ResourceManager.GetObject("next", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap paint {
			get {
				object obj = ResourceManager.GetObject("paint", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap pastfile {
			get {
				object obj = ResourceManager.GetObject("pastfile", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap pause {
			get {
				object obj = ResourceManager.GetObject("pause", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap pictures {
			get {
				object obj = ResourceManager.GetObject("pictures", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap play {
			get {
				object obj = ResourceManager.GetObject("play", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap printer {
			get {
				object obj = ResourceManager.GetObject("printer", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap printpreview {
			get {
				object obj = ResourceManager.GetObject("printpreview", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap redo {
			get {
				object obj = ResourceManager.GetObject("redo", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap refresh {
			get {
				object obj = ResourceManager.GetObject("refresh", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap saveas {
			get {
				object obj = ResourceManager.GetObject("saveas", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap stats {
			get {
				object obj = ResourceManager.GetObject("stats", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap stop {
			get {
				object obj = ResourceManager.GetObject("stop", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap textfile {
			get {
				object obj = ResourceManager.GetObject("textfile", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap trash {
			get {
				object obj = ResourceManager.GetObject("trash", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap trashb {
			get {
				object obj = ResourceManager.GetObject("trashb", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap undo {
			get {
				object obj = ResourceManager.GetObject("undo", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap up {
			get {
				object obj = ResourceManager.GetObject("up", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap user {
			get {
				object obj = ResourceManager.GetObject("user", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap userb {
			get {
				object obj = ResourceManager.GetObject("userb", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap userid {
			get {
				object obj = ResourceManager.GetObject("userid", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap userlock {
			get {
				object obj = ResourceManager.GetObject("userlock", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap web {
			get {
				object obj = ResourceManager.GetObject("web", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap webhd {
			get {
				object obj = ResourceManager.GetObject("webhd", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap weblocked {
			get {
				object obj = ResourceManager.GetObject("weblocked", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap weboptions {
			get {
				object obj = ResourceManager.GetObject("weboptions", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap websearch {
			get {
				object obj = ResourceManager.GetObject("websearch", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap window {
			get {
				object obj = ResourceManager.GetObject("window", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap windowb {
			get {
				object obj = ResourceManager.GetObject("windowb", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap wizard {
			get {
				object obj = ResourceManager.GetObject("wizard", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap zoomin {
			get {
				object obj = ResourceManager.GetObject("zoomin", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap zoomout {
			get {
				object obj = ResourceManager.GetObject("zoomout", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
